kind: pipeline
type: docker
name: packmaker

workspace:
  path: /drone/src

steps:
- name: pre-lock
  image: kalka/drone-entrypoint
  commands:
  - git clone https://git.kalka.io/kalka/wolfpackmaker
  - neofetch
  - python3 -VVV
- name: lock
  image: kalka/drone-entrypoint
  commands:
  - python3 wolfpackmaker/util/lock.py
- name: package
  image: kalka/drone-entrypoint
  commands:
  - zip -r Wolfpack-Odin.zip wolfpackmaker/wolfpackmaker.py wolfpackmaker/wolfpackmaker.bat wolfpackmaker/requirements.txt wolfpackmaker/multimc.bat .minecraft instance.cfg mmc-pack.json wolfpackodin.png
  - zip -r config.zip .minecraft mmc-pack.json
- name: mod-list
  image: kalka/drone-entrypoint
  commands:
  - python3 wolfpackmaker/util/raw_mod_list.py Odin
- name: upload
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_key
    files:
      - Wolfpack-Odin.zip
      - config.zip
      - manifest.lock
      - manifest.json
      - modlist.db
  when:
    event: tag

    