
#General settings for the mod.
[general]
	#The color at the top of the tooltip gradient.
	borderStart = "a07a0505"
	#The color at the bottom of the tooltip gradient.
	borderEnd = "a0782a12"
	#The color for the background of the tooltip.
	background = "c0260303"

