
name: Wolfpack-Odin

on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v2
      - run: pacman -Syyu --noconfirm python3 git zip
      - run: git clone https://github.com/kalkafox/wolfpackmaker.git
      - run: python3 -VVV
      - run: python3 -m ensurepip
      - run: python3 -m pip install -r wolfpackmaker/requirements.txt
      - run: python3 wolfpackmaker/util/lock.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            manifest.*
            *.zip
