
name: Wolfpack-Odin

on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    container:
      image: archlinux
    steps:
      - run: pacman -Syyu --noconfirm python3
      - run: python3 -VVV
  build-2:
    runs-on: self-hosted
    container:
      image: archlinux
    steps:
      - run: echo test
      - run: python -VVV
